### ISSUE TITLE
Can't open exe

### ISSUE THREAD

**Issue by Anonymous1381938** [milankarman/fast-stronghold#2]
https://imgur.com/yrFeugK

**Comment by milankarman** [comment]
Hey. I think this could have been either a dependency issue or an issue with the program failing to make itself always on top or disabling quick edit.

Please try [v.1.0.3](https://github.com/milankarman/fast-stronghold/releases/tag/v1.0.3) which I pushed just now. FastStronghold is now self contained meaning all dependencies are included, so if that was the problem that should be resolved. And failure of the window setting itself always on top and disabling quick edit should now be handled properly. So if that was the problem that should be resolved now too.

Please let me know if it resolved your issues.

**Comment by Anonymous1381938** [comment]
v1.0.3 has resolved the problem.
