### ISSUE TITLE
Feature Request: Best Blind Travel

### ISSUE THREAD

**Issue by DylanCope** [milankarman/fast-stronghold#4]
When pressing F3+C in the nether for the second time, instead of the distance to the original nether portal, could we have a suggested location to blind travel? I.e. the closest point in the nether to stronghold ring. 

I suggest getting rid of the distance because that seems the most redundant given all the other information, but maybe people like it so it could be configurable.

**Comment by milankarman** [comment]
Sounds useful, I'll get to work on that very soon. I don't expect it to take too long to add.

**Comment by milankarman** [comment]
Added to release [1.2.0](https://github.com/milankarman/fast-stronghold/releases/tag/1.2.0). I'd love to hear your experience with it if you get a chance to try it.

**Comment by DylanCope** [comment]
I just tried it out! Great job and I'm amazed how quickly you got that done :)
